### PR TITLE
Single-reader analysis

### PR DESCRIPTION
**Pull request by koyousun**

### CODE REVIEW

**Comment by brandon-gallas** [comment]
Yousun,

I received this pull request. Does it mean that your work is ready to be merged with the base trunk?
If so, could you  summarize what are the main changes (visually or operationally for the end user) to the software?

Brandon

**Comment by koyousun** [comment]
Sorry for not explaining what I have done. The source code I revised is able to analyze single-reader data based on the equation A.25 in Gallas 2006. 
-	A tap is added for single-reader analysis. The result appears in the table in the same way of multi-reader BDG result except M5, M6, M7, and M8 columns.
-	Single BDG Tab is automatically selected when you use data of single-reader.
-	In the source code, almost every member variable and functions related to multi-reader BDG is duplicated and then renamed. E.g. totalVarMLESingle as totalVarMLE, SingleBDGforStatPanel like BDGforStatPanel, etc. That was how I changed the source code to minimize the impact of my code to the previous commit just in case that there is something wrong with my code.
-	I guess you might be interested in the DBRecord.genSingleBDGCoeff method and the SingleBDGv variable in the StatPanel.setTable1 – how values are calculated. 
I hope this will explain it. Please check the revised source code. 

Thank you, 
Yousun.

**Comment by brandon-gallas** [comment]
That sounds great.
@qigongFDA is going to check what you have done as an end user and as a developer.

Have you done any validation of your work?
We really need some in order to pull it into the base:master.
If you want, you can use iRoeMetz to accomplish this. @qigongFDA is about to update iRoeMetz, so you should wait to see what that looks like and to pull those changes into your fork.
We can help with this, but it is going to have to wait until after SPIE-Medical Imaging conference (March 5).

**Comment by brandon-gallas** [comment]
Your pull request is old. I'm sorry that I didn't follow up before now. Your comments and code informed us on a path forward. Thanks so much. I hope you are well.

**Pull request closed without merging**
